### ISSUE TITLE
CodeSign isnt working

### ISSUE THREAD

**Issue by arcinston** [lando/code-sign-action#5]
<img width="770" alt="image" src="https://github.com/lando/code-sign-action/assets/69193694/544bb332-ecb8-45f5-a403-09960a88a057">

apologies for the poorly documented issue

but i added everytime neceesary but the code still fails with this error

if you caould help me with what the actual issue is i can try solving it

**Comment by sestinj** [comment]
@arcinston I'm running into the same thing...is there any chance you ended up finding a solution here?

**Comment by arcinston** [comment]
hey @sestinj 

this is what i did 
<img width="617" alt="image" src="https://github.com/user-attachments/assets/fc5bff93-8727-45f2-87da-947e627d384d">
<img width="580" alt="image" src="https://github.com/user-attachments/assets/3545424c-b352-469e-9161-868cdf15c17d">

hope this helps

**Comment by sestinj** [comment]
Thanks so much!! Can't tell you how helpful this was : )
